export const documentos = [
  {
    id: 1,
    tipo: 'Ordenanza',
    nombre: 'Ordenanza Municipal N° 005-2025-MDNCH',
    fecha: '15 Ene 2025',
    enlace: '#',
    color: 'blue',
  },
  {
    id: 2,
    tipo: 'Reglamento',
    nombre: 'Reglamento del Presupuesto Participativo con enfoque Multianual 2023 - 2025',
    fecha: '10 Ene 2025',
    enlace: '#',
    color: 'green',
  },
  {
    id: 3,
    tipo: 'Decreto',
    nombre: 'Decreto de Alcaldía N° 002-2025-MDNCH',
    fecha: '08 Ene 2025',
    enlace: '#',
    color: 'orange',
  },
  {
    id: 4,
    tipo: 'Convocatoria',
    nombre: 'Convocatoria al presupuesto participativo 2025',
    fecha: '05 Ene 2025',
    enlace: '#',
    color: 'blue',
  },
  {
    id: 5,
    tipo: 'Formulario',
    nombre: 'Registro de participantes',
    fecha: '03 Ene 2025',
    enlace: '#',
    color: 'green',
  },
  {
    id: 6,
    tipo: 'Guía',
    nombre: 'Criterios de Priorización',
    fecha: '02 Ene 2025',
    enlace: '#',
    color: 'orange',
  },
  {
    id: 7,
    tipo: 'Formulario',
    nombre: 'Ficha de Inversión',
    fecha: '01 Ene 2025',
    enlace: '#',
    color: 'orange',
  },
];
