export const regidores = [
	{
		id: 1,
		numero: 1,
		cargo: 'Regidor 1',
		nombre: 'Milagritos Karina Manrique Quipusco',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Asuntos Legales y Secretaría General', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Carlos Mendoza', cargo: 'Asistente' },
			{ nombre: 'María López', cargo: 'Secretaria' },
		],
	},
	{
		id: 2,
		numero: 2,
		cargo: 'Regidor 2',
		nombre: 'Julio Cesar Maceda Cruzado',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Desarrollo Urbano', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Pedro Ramírez', cargo: 'Asistente' },
			{ nombre: 'Ana Torres', cargo: 'Secretaria' },
		],
	},
	{
		id: 3,
		numero: 3,
		cargo: 'Regidor 3',
		nombre: 'Zoila Renee Villanueva Calonge',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Asuntos Legales y Secretaría General', cargo: 'Primer Miembro' }],
		equipo: [
			{ nombre: 'Juan Pérez', cargo: 'Asistente' },
			{ nombre: 'Lucía Gómez', cargo: 'Secretaria' },
		],
	},
	{
		id: 4,
		numero: 4,
		cargo: 'Regidor 4',
		nombre: 'Abel Dino Palma León',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Asuntos Legales y Secretaría General', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Roberto Sánchez', cargo: 'Asistente' },
			{ nombre: 'Carmen Díaz', cargo: 'Secretaria' },
		],
	},
	{
		id: 5,
		numero: 5,
		cargo: 'Regidor 5',
		nombre: 'Diana Katherine Manrique Muguerza',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Administración, Planeamiento y Presupuesto', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Fernando Castro', cargo: 'Asistente' },
			{ nombre: 'Patricia Ruiz', cargo: 'Secretaria' },
		],
	},
	{
		id: 6,
		numero: 6,
		cargo: 'Regidor 6',
		nombre: 'Jorge Raul Gomez Arana',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Servicios Públicos', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Miguel Ángel Rojas', cargo: 'Asistente' },
			{ nombre: 'Sofía Vargas', cargo: 'Secretaria' },
		],
	},
	{
		id: 7,
		numero: 7,
		cargo: 'Regidor 7',
		nombre: 'Diana Anghella Cueva Melgarejo',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Desarrollo Social', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Javier Morales', cargo: 'Asistente' },
			{ nombre: 'Claudia Ortiz', cargo: 'Secretaria' },
		],
	},
	{
		id: 8,
		numero: 8,
		cargo: 'Regidor 8',
		nombre: 'Beatriz Madrid Amayo',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Cultura y Educación', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Raúl Jiménez', cargo: 'Asistente' },
			{ nombre: 'Valeria Campos', cargo: 'Secretaria' },
		],
	},
	{
		id: 9,
		numero: 9,
		cargo: 'Regidor 9',
		nombre: 'Juan Augusto Zavaleta Pinedo',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Administración, Planeamiento y Presupuesto', cargo: 'Segundo Miembro' }],
		equipo: [
			{ nombre: 'Ernesto Vega', cargo: 'Asistente' },
			{ nombre: 'Gabriela Paredes', cargo: 'Secretaria' },
		],
	},
	{
		id: 10,
		numero: 10,
		cargo: 'Regidor 10',
		nombre: 'Susana Margarita Bustillos Oyanguren',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Medio Ambiente', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Daniel Flores', cargo: 'Asistente' },
			{ nombre: 'Natalia Rivas', cargo: 'Secretaria' },
		],
	},
	{
		id: 11,
		numero: 11,
		cargo: 'Regidor 11',
		nombre: 'Ronald Javier Nieto Gallo',
		foto: '/Daniel.jpg',
		comisiones: [{ nombre: 'Comisión de Seguridad Ciudadana', cargo: 'Presidente' }],
		equipo: [
			{ nombre: 'Alejandro Medina', cargo: 'Asistente' },
			{ nombre: 'Isabel Herrera', cargo: 'Secretaria' },
		],
	},
];
